name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2 vim maven curl git mysql-server

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: 'movin' 
          mysql user: 'group8'
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clone the project repository
        run: git clone https://github.com/cse364-unist/projects-group8.git

      - name: Checkout master
        run: |
          cd projects-group8/movinProject
          git checkout master

      - name: Add API key to application.properties
        run: echo "openai.api.key=${{secrets.OPENAI_KEY}}" >> ./projects-group8/movinProject/src/main/resources/application.properties

      - name: Build and test project with Maven
        run: |
          cd projects-group8/movinProject
          mvn jacoco:report
          mvn package

      # - name: Run the Spring Boot application
      #   run: |
      #     cd projects-group8/movinProject
      #     java -jar target/movinProject-0.0.1-SNAPSHOT-with-dependencies.jar
